### ISSUE TITLE
盤面の外を選択した場合に例外が発生する

### ISSUE THREAD

**Issue by yfujii01** [yuto-nago/Reversi2#2]
@yuto-nago 

以下のケースで例外が発生するので修正をお願いします。

   0  1  2  3  4  5  6  7  
0  ＊ ＊ ＊ ＊ ＊ ＊ ＊ ＊ 
10 ＊ ○ ● ＊ ＊ ＊ ＊ ＊ 
20 ＊ ＊ ○ ＊ ＊ ＊ ＊ ＊ 
30 ＊ ＊ ● ○ ● ＊ ＊ ＊ 
40 ＊ ＊ ＊ ● ○ ● ＊ ＊ 
50 ＊ ＊ ＊ ＊ ＊ ○ ＊ ＊ 
60 ＊ ＊ ＊ ＊ ＊ ● ○ ＊ 
70 ＊ ＊ ＊ ＊ ＊ ＊ ＊ ＊ 
●のターン
石を置く場所を指定してください49
Exception in thread "main" java.lang.ArrayIndexOutOfBoundsException: 9
	at kenshu.GamePlay.put_check(GamePlay.java:1681)
	at kenshu.GamePlay.play(GamePlay.java:73)
	at kenshu.Main.main(Main.java:11)

**Comment by yfujii01** [comment]
acddb12d05a539ea6594faa567aa8cc4f9532ea4
で解決
